version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "1234:5432"
    container_name: lms_db
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: apazev09