server:
  port: 8080
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  main:
    allow-circular-references: true
  application:
    name: "lms_service"
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/lms_db
    username: bob
    password: apazev09
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true